{
	"name": "M_Debug",
	"type": "material",
	"version": 1,
	"desc": "Material from TiX exporter.",
	"shaders": [
		"S_ParticlesVS",
		"S_ParticlesPS",
		"",
		"",
		""
	],
	"topology": "EPT_POINTLIST",
	"vs_format": [
		"EVSSEG_POSITION"
	],
	"rt_colors": [
		"EPF_RGBA16F"
	],
	"rt_depth": "EPF_DEPTH24_STENCIL8",
	"blend_mode": "BLEND_MODE_OPAQUE",
	"depth_write": true,
	"depth_test": true,
	"two_sides": true
}