{
	"name": "M_AddSpecular",
	"type": "material",
	"version": 1,
	"desc": "",
	"shaders": [
		"S_AddSpecularVS.cso",
		"S_AddSpecularPS.cso",
		"",
		"",
		""
	],
	"vs_format": [
		"EVSSEG_POSITION",
		"EVSSEG_TEXCOORD0"
	],
	"rt_colors": [
		"EPF_RGBA16F"
	],
	"rt_depth": "",
	"shader_binding": "SB_AddSpecular.tres",
	"blend_mode": "BLEND_MODE_OPAQUE",
	"depth_write": false,
	"depth_test": false,
	"two_sides": false
}