{
	"name": "M_SkinBase",
	"type": "material",
	"version": 1,
	"desc": "",
	"shaders": [
		"SkinBaseVS.cso",
		"SkinBasePS.cso",
		"",
		"",
		""
	],
	"vs_format": [
		"EVSSEG_POSITION",
		"EVSSEG_NORMAL",
		"EVSSEG_TEXCOORD0",
		"EVSSEG_TANGENT"
	],
	"rt_colors": [
		"EPF_BGRA8"
	],
	"rt_depth": "EPF_DEPTH24_STENCIL8",
	"shader_binding": "MPB_SkinBase.tres",
	"blend_mode": "BLEND_MODE_OPAQUE",
	"depth_write": true,
	"depth_test": true,
	"two_sides": false
}