{
	"name": "SB_SkinBase",
	"type": "shader_binding",
	"version": 1,
	"desc": "",
	"parameters": 
	[
		{
			"type": "BINDING_UNIFORMBUFFER",
			"stage": "ESS_VERTEX_SHADER",
			"register": 0
		},
		{
			"type": "BINDING_UNIFORMBUFFER",
			"stage": "ESS_PIXEL_SHADER",
			"register": 4
		},
		{
			"type": "BINDING_LIGHTS",
			"stage": "ESS_PIXEL_SHADER",
			"register": 5
		},
		{
			"type": "BINDING_TEXTURE_TABLE",
			"stage": "ESS_PIXEL_SHADER",
			"register": 0,
			"size": 5
		}
	]
}