{
	"name": "SB_SkinBase",
	"type": "shader_binding",
	"version": 1,
	"desc": "",
	"parameters": 
	[
		{
			"type": "BINDING_UNIFORMBUFFER",
			"stage": "ESS_VERTEX_SHADER"
		},
		{
			"type": "BINDING_UNIFORMBUFFER",
			"stage": "ESS_PIXEL_SHADER"
		},
		{
			"type": "BINDING_UNIFORMBUFFER",
			"stage": "ESS_PIXEL_SHADER"
		},
		{
			"type": "BINDING_TEXTURE_TABLE",
			"stage": "ESS_PIXEL_SHADER",
			"size": 5
		}
	]
}