/*
	TiX Engine v2.0 Copyright (C) 2018
	By ZhaoShuai tirax.cn@gmail.com
*/

#pragma once

namespace tix
{
	enum E_PIXEL_FORMAT
	{
		EPF_L8,
		EPF_L16,
		EPF_A8,
		EPF_R5G6B5,
		EPF_A4R4G4B4,
		EPF_R4G4B4A4,
		EPF_A1R5G5B5,
		EPF_R5G5B5A1,
		EPF_R8G8B8,
		EPF_B8G8R8,
		EPF_A8R8G8B8,
		EPF_B8G8R8A8,
		EPF_R8G8B8A8,
		EPF_A8B8G8R8,

		// DXT formats
		EPF_COMPRESSED_RGB_S3TC_DXT1,
		EPF_COMPRESSED_RGBA_S3TC_DXT1,
		EPF_COMPRESSED_RGBA_S3TC_DXT3,
		EPF_COMPRESSED_RGBA_S3TC_DXT5,

		// PVR formats
		EPF_COMPRESSED_sRGB_PVRTC_4BPP,
		EPF_COMPRESSED_sRGB_Alpha_PVRTC_4BPP,
		EPF_COMPRESSED_RGB_PVRTC_4BPP,
		EPF_COMPRESSED_RGBA_PVRTC_4BPP,

		// ETC format
		EPF_COMPRESSED_ETC,

		// Float formats
		EPF_RGB16F,
		EPF_RGBA16F,
		EPF_RG32F,
		EPF_RGB32F,
		EPF_RGBA32F,

		// Other formats
		EPF_DEPTH16,
		EPF_DEPTH24,
		EPF_DEPTH32,
		EPF_DEPTH24_STENCIL8,
		EPF_STENCIL1,
		EPF_STENCIL4,
		EPF_STENCIL8,

		EPF_SRGB8,
		EPF_SRGB8_ALPHA,

		EPF_R16F,
		EPF_R32F,

		EPF_UNKNOWN,
		EPF_COUNT
	};

	enum E_PIXEL_COMPONENT_TYPE
	{
		EPCT_BYTE,
		EPCT_SHORT,
		EPCT_INT32,
		EPCT_FLOAT16,
		EPCT_FLOAT32,

		EPCT_COUNT,
		EPCT_UNKNOWN = uint8(-1)
	};

	enum E_PIXEL_FORMAT_FLAGS
	{
		EPFF_ALPHA = 1,
		EPFF_FLOAT = EPFF_ALPHA << 1,
		EPFF_LUMINANCE = EPFF_FLOAT << 1,
		EPFF_COMPRESSED = EPFF_LUMINANCE << 1,
		EPFF_DEPTH = EPFF_COMPRESSED << 1,
		EPFF_STENCIL = EPFF_DEPTH << 1,
		EPFF_PACKED = EPFF_STENCIL << 1
	};

	enum E_PIXEL_COMPONENT
	{
		EPC_RED,
		EPC_GREEN,
		EPC_BLUE,
		EPC_ALPHA,

		EPC_COUNT
	};
}