{
	"name": "M_DepthOnly",
	"type": "material",
	"version": 1,
	"desc": "Material from TiX exporter.",
	"shaders": [
		"S_DepthOnlyVS",
		"",
		"",
		"",
		""
	],
	"vs_format": [
		"EVSSEG_POSITION"
	],
	"ins_format": [
		"EINSSEG_TRANSITION",
		"EINSSEG_ROT_SCALE_MAT0",
		"EINSSEG_ROT_SCALE_MAT1",
		"EINSSEG_ROT_SCALE_MAT2"
	],
	"rt_colors": [
	],
	"rt_depth": "EPF_DEPTH32",
	"blend_mode": "BLEND_MODE_OPAQUE",
	"depth_write": true,
	"depth_test": true,
	"two_sides": false
}