{
	"name": "RTX_Pathtracer",
	"type": "rtx_pipeline",
	"version": 1,
	"desc": "RTX pipeline define, created manually.",
	"shader_lib": "S_Pathtracer",
	"export_names" : [
		"MyRayGenShader",
		"RayMiss",
		"RayClosestHit",
		"RayAnyHit"
	],
	"hit_group_name" : "MyHitGroup",
	"hit_group" : [
		"RayAnyHit",
		"RayClosestHit",
		""
	],
	"max_attribute_size_in_bytes" : 8,
	"max_payload_size_in_bytes" : 16,
	"max_trace_recursion_depth" : 1
}